const sampleProducts = [
  // ===== WOMEN'S DRESSES (10) =====
  {
    name: "Elegant Evening Gown",
    description: "A stunning floor-length evening gown in premium silk with beaded detailing.",
    category: "Women's Dresses",
    price: 249.99,
    discountPrice: 189.99,
    images: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy", "Emerald"],
    stock: 15,
    rating: 4.8,
    material: "100% Premium Silk",
    sku: "DRS-W001"
  },
  {
    name: "Floral Midi Sundress",
    description: "Breezy midi-length sundress with vibrant floral print and side pockets.",
    category: "Women's Dresses",
    price: 79.99,
    discountPrice: 59.99,
    images: ["https://images.unsplash.com/photo-1612336307429-8a88e8d08dbb?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Floral Pink", "Floral Blue", "White"],
    stock: 45,
    rating: 4.6,
    material: "100% Rayon",
    sku: "DRS-W002"
  },
  {
    name: "Little Black Dress",
    description: "The ultimate LBD with fitted bodice, flared A-line skirt, and keyhole back detail.",
    category: "Women's Dresses",
    price: 119.99,
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy"],
    stock: 30,
    rating: 4.7,
    material: "95% Polyester, 5% Elastane",
    sku: "DRS-W003"
  },
  {
    name: "Wrap Bodycon Dress",
    description: "Flattering wrap-style bodycon dress with stretchy fabric.",
    category: "Women's Dresses",
    price: 89.99,
    discountPrice: 69.99,
    images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Red", "Royal Blue"],
    stock: 50,
    rating: 4.5,
    material: "92% Polyester, 8% Spandex",
    sku: "DRS-W004"
  },
  {
    name: "Bohemian Maxi Dress",
    description: "Free-spirited bohemian maxi dress with intricate patterns.",
    category: "Women's Dresses",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1595607774223-ef52624120d2?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Multicolor", "Orange", "Blue"],
    stock: 28,
    rating: 4.4,
    material: "100% Viscose",
    sku: "DRS-W005"
  },
  {
    name: "Shirt Dress",
    description: "Classic shirt dress that doubles as a jacket with button-front.",
    category: "Women's Dresses",
    price: 79.99,
    discountPrice: 64.99,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Denim", "White", "Khaki"],
    stock: 45,
    rating: 4.6,
    material: "100% Cotton",
    sku: "DRS-W006"
  },
  {
    name: "Sequin Party Dress",
    description: "Eye-catching sequin dress with fully sequined fabric.",
    category: "Women's Dresses",
    price: 129.99,
    discountPrice: 99.99,
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Silver", "Gold", "Black"],
    stock: 20,
    rating: 4.7,
    material: "100% Polyester",
    sku: "DRS-W007"
  },
  {
    name: "Linen Summer Dress",
    description: "Lightweight linen dress perfect for warm weather.",
    category: "Women's Dresses",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1591555780332-8651f59dba2e?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Beige", "Light Blue"],
    stock: 40,
    rating: 4.5,
    material: "100% Linen",
    sku: "DRS-W008"
  },
  {
    name: "Puff Sleeve Dress",
    description: "Romantic dress with dramatic puff sleeves and fitted bodice.",
    category: "Women's Dresses",
    price: 119.99,
    discountPrice: 94.99,
    images: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Red", "Pink", "Navy"],
    stock: 25,
    rating: 4.6,
    material: "95% Cotton, 5% Elastane",
    sku: "DRS-W009"
  },
  {
    name: "Slip Dress",
    description: "Silky slip dress with delicate straps, perfect for layering.",
    category: "Women's Dresses",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Champagne", "Blush"],
    stock: 50,
    rating: 4.7,
    material: "100% Satin",
    sku: "DRS-W010"
  },

  // ===== WOMEN'S TOPS (10) =====
  {
    name: "Cashmere Blend Sweater",
    description: "Luxuriously soft cashmere blend sweater with relaxed fit.",
    category: "Women's Tops",
    price: 149.99,
    discountPrice: 119.99,
    images: ["https://images.unsplash.com/photo-1556821840-9c63d3f02f65?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Gray", "Navy", "Black"],
    stock: 35,
    rating: 4.9,
    material: "50% Cashmere, 50% Merino",
    sku: "TOP-W001"
  },
  {
    name: "Classic White T-Shirt",
    description: "Perfect everyday white t-shirt, essential wardrobe staple.",
    category: "Women's Tops",
    price: 34.99,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Navy", "Gray"],
    stock: 100,
    rating: 4.6,
    material: "100% Cotton",
    sku: "TOP-W002"
  },
  {
    name: "Button-Up Blouse",
    description: "Versatile button-up blouse for office or casual wear.",
    category: "Women's Tops",
    price: 64.99,
    discountPrice: 49.99,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Light Blue", "Black"],
    stock: 60,
    rating: 4.7,
    material: "100% Cotton",
    sku: "TOP-W003"
  },
  {
    name: "Crop Top",
    description: "Trendy crop top perfect for a fun, youthful look.",
    category: "Women's Tops",
    price: 29.99,
    images: ["https://images.unsplash.com/photo-1505691938895-48ce2ae61914?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "White", "Pink"],
    stock: 75,
    rating: 4.4,
    material: "95% Cotton, 5% Elastane",
    sku: "TOP-W004"
  },
  {
    name: "Oversized Sweatshirt",
    description: "Comfortable oversized sweatshirt perfect for lounging.",
    category: "Women's Tops",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1556821840-9c63d3f02f65?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Gray", "Black", "Charcoal", "Navy"],
    stock: 70,
    rating: 4.6,
    material: "80% Cotton, 20% Polyester",
    sku: "TOP-W005"
  },
  {
    name: "Silk Camisole",
    description: "Luxurious silk camisole for elegant sophistication.",
    category: "Women's Tops",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Champagne", "Blush"],
    stock: 40,
    rating: 4.8,
    material: "100% Silk",
    sku: "TOP-W006"
  },
  {
    name: "Sequin Top",
    description: "Sparkly sequin top for special occasions and parties.",
    category: "Women's Tops",
    price: 74.99,
    images: ["https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Silver", "Gold", "Black"],
    stock: 25,
    rating: 4.7,
    material: "80% Polyester, 20% Nylon",
    sku: "TOP-W007"
  },
  {
    name: "Off-Shoulder Blouse",
    description: "Romantic off-shoulder blouse with bell sleeves.",
    category: "Women's Tops",
    price: 64.99,
    discountPrice: 49.99,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Black", "Red"],
    stock: 35,
    rating: 4.8,
    material: "100% Cotton",
    sku: "TOP-W008"
  },
  {
    name: "Fitted Turtleneck",
    description: "Classic turtleneck in fitted silhouette.",
    category: "Women's Tops",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1556821840-9c63d3f02f65?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Cream"],
    stock: 55,
    rating: 4.7,
    material: "100% Cotton",
    sku: "TOP-W009"
  },
  {
    name: "Lace Tank Top",
    description: "Delicate lace tank top perfect for layering.",
    category: "Women's Tops",
    price: 44.99,
    images: ["https://images.unsplash.com/photo-1515120573856-e9a1e95dcd66?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Nude"],
    stock: 60,
    rating: 4.6,
    material: "90% Nylon, 10% Elastane",
    sku: "TOP-W010"
  },

  // ===== WOMEN'S BOTTOMS (10) =====
  {
    name: "Premium Denim Jeans",
    description: "Classic fit premium denim jeans with perfect stretch.",
    category: "Women's Bottoms",
    price: 99.99,
    discountPrice: 79.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Light Blue", "Dark Blue", "Black"],
    stock: 50,
    rating: 4.8,
    material: "98% Cotton, 2% Elastane",
    sku: "BTM-W001"
  },
  {
    name: "High-Waist Shorts",
    description: "Chic high-waist shorts perfect for summer.",
    category: "Women's Bottoms",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Khaki"],
    stock: 70,
    rating: 4.6,
    material: "97% Cotton, 3% Elastane",
    sku: "BTM-W002"
  },
  {
    name: "Elegant Maxi Skirt",
    description: "Long flowing maxi skirt in premium fabric.",
    category: "Women's Bottoms",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1591520591413-2b5ffb4a4d3e?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy"],
    stock: 45,
    rating: 4.7,
    material: "100% Polyester",
    sku: "BTM-W003"
  },
  {
    name: "Flowy Linen Pants",
    description: "Comfortable flowy pants perfect for warm weather.",
    category: "Women's Bottoms",
    price: 74.99,
    images: ["https://images.unsplash.com/photo-1517622614260-3eb27419b5ba?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Olive"],
    stock: 65,
    rating: 4.5,
    material: "100% Linen",
    sku: "BTM-W004"
  },
  {
    name: "Leather Pants",
    description: "Edgy leather pants for bold statement looks.",
    category: "Women's Bottoms",
    price: 149.99,
    images: ["https://images.unsplash.com/photo-1548844519-f7cfcd3b0f3e?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Brown"],
    stock: 20,
    rating: 4.6,
    material: "100% Leather",
    sku: "BTM-W005"
  },
  {
    name: "Pencil Skirt",
    description: "Classic pencil skirt perfect for office wear.",
    category: "Women's Bottoms",
    price: 64.99,
    images: ["https://images.unsplash.com/photo-1591520591413-2b5ffb4a4d3e?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Gray", "Navy"],
    stock: 55,
    rating: 4.7,
    material: "95% Polyester, 5% Spandex",
    sku: "BTM-W006"
  },
  {
    name: "Distressed Denim Shorts",
    description: "Trendy distressed denim shorts with stylish rips.",
    category: "Women's Bottoms",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Light Blue", "Dark Blue"],
    stock: 60,
    rating: 4.4,
    material: "98% Cotton, 2% Elastane",
    sku: "BTM-W007"
  },
  {
    name: "Wide Leg Trousers",
    description: "Elegant wide-leg trousers for sophisticated look.",
    category: "Women's Bottoms",
    price: 84.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Gray", "Navy"],
    stock: 50,
    rating: 4.8,
    material: "87% Polyester, 13% Elastane",
    sku: "BTM-W008"
  },
  {
    name: "Cargo Pants",
    description: "Utility-inspired cargo pants with multiple pockets.",
    category: "Women's Bottoms",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1517622614260-3eb27419b5ba?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Olive", "Black", "Navy"],
    stock: 48,
    rating: 4.5,
    material: "100% Cotton",
    sku: "BTM-W009"
  },
  {
    name: "Pleated Midi Skirt",
    description: "Sophisticated pleated midi skirt with timeless appeal.",
    category: "Women's Bottoms",
    price: 74.99,
    images: ["https://images.unsplash.com/photo-1591520591413-2b5ffb4a4d3e?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Cream"],
    stock: 52,
    rating: 4.8,
    material: "100% Polyester",
    sku: "BTM-W010"
  },

  // ===== WOMEN'S OUTERWEAR (10) =====
  {
    name: "Black Leather Jacket",
    description: "Timeless black leather jacket, wardrobe essential.",
    category: "Women's Outerwear",
    price: 249.99,
    discountPrice: 199.99,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black"],
    stock: 20,
    rating: 4.9,
    material: "100% Leather",
    sku: "OUT-W001"
  },
  {
    name: "Wool Cardigan",
    description: "Cozy wool cardigan perfect for layering.",
    category: "Women's Outerwear",
    price: 129.99,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Gray", "Navy", "Beige"],
    stock: 35,
    rating: 4.8,
    material: "80% Wool, 20% Nylon",
    sku: "OUT-W002"
  },
  {
    name: "Denim Jacket",
    description: "Classic denim jacket that never goes out of style.",
    category: "Women's Outerwear",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Blue", "Medium Blue", "Dark Blue"],
    stock: 55,
    rating: 4.7,
    material: "100% Denim",
    sku: "OUT-W003"
  },
  {
    name: "Trench Coat",
    description: "Sophisticated trench coat for elegant style.",
    category: "Women's Outerwear",
    price: 189.99,
    discountPrice: 149.99,
    images: ["https://images.unsplash.com/photo-1539533057440-7bf05ad00029?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Beige", "Camel", "Black"],
    stock: 30,
    rating: 4.9,
    material: "65% Polyester, 35% Cotton",
    sku: "OUT-W004"
  },
  {
    name: "Puffer Jacket",
    description: "Warm and cozy puffer jacket for cold weather.",
    category: "Women's Outerwear",
    price: 149.99,
    discountPrice: 119.99,
    images: ["https://images.unsplash.com/photo-1545307352-956f3b3e1f80?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Red"],
    stock: 40,
    rating: 4.8,
    material: "100% Nylon",
    sku: "OUT-W005"
  },
  {
    name: "Blazer",
    description: "Classic structured blazer for work and formal.",
    category: "Women's Outerwear",
    price: 139.99,
    images: ["https://images.unsplash.com/photo-1539533057440-7bf05ad00029?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy"],
    stock: 38,
    rating: 4.9,
    material: "95% Polyester, 5% Elastane",
    sku: "OUT-W006"
  },
  {
    name: "Bomber Jacket",
    description: "Trendy bomber jacket with sleek silhouette.",
    category: "Women's Outerwear",
    price: 99.99,
    discountPrice: 79.99,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Olive"],
    stock: 45,
    rating: 4.6,
    material: "100% Polyester",
    sku: "OUT-W007"
  },
  {
    name: "Faux Fur Coat",
    description: "Luxurious faux fur coat for glamorous style.",
    category: "Women's Outerwear",
    price: 199.99,
    images: ["https://images.unsplash.com/photo-1545307352-956f3b3e1f80?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "White", "Brown"],
    stock: 15,
    rating: 4.8,
    material: "100% Acrylic",
    sku: "OUT-W008"
  },
  {
    name: "Wool Coat",
    description: "Elegant wool coat perfect for winter style.",
    category: "Women's Outerwear",
    price: 219.99,
    discountPrice: 179.99,
    images: ["https://images.unsplash.com/photo-1545307352-956f3b3e1f80?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Camel", "Navy"],
    stock: 25,
    rating: 4.9,
    material: "80% Wool, 20% Polyester",
    sku: "OUT-W009"
  },
  {
    name: "Windbreaker",
    description: "Practical windbreaker for active wear.",
    category: "Women's Outerwear",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Red"],
    stock: 50,
    rating: 4.5,
    material: "100% Polyester",
    sku: "OUT-W010"
  },

  // ===== MEN'S SHIRTS (10) =====
  {
    name: "Classic Oxford Shirt",
    description: "Timeless white Oxford shirt perfect for business casual.",
    category: "Men's Shirts",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1596400564269-f1a8b3c0ed47?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Light Blue", "Navy"],
    stock: 65,
    rating: 4.8,
    material: "100% Cotton",
    sku: "MEN-SH001"
  },
  {
    name: "Casual Button-Down",
    description: "Comfortable casual button-down shirt for everyday wear.",
    category: "Men's Shirts",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1596400564269-f1a8b3c0ed47?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Checked Red", "Plaid Navy", "Striped Blue"],
    stock: 75,
    rating: 4.6,
    material: "100% Cotton",
    sku: "MEN-SH002"
  },
  {
    name: "White T-Shirt",
    description: "Essential white t-shirt for everyday wear.",
    category: "Men's Shirts",
    price: 29.99,
    images: ["https://images.unsplash.com/photo-1535687930308-53d9118c670a?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Gray"],
    stock: 120,
    rating: 4.7,
    material: "100% Cotton",
    sku: "MEN-SH003"
  },
  {
    name: "Polo Shirt",
    description: "Classic polo shirt perfect for casual and smart casual.",
    category: "Men's Shirts",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1596400564269-f1a8b3c0ed47?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "White", "Black", "Red"],
    stock: 70,
    rating: 4.7,
    material: "100% Cotton",
    sku: "MEN-SH004"
  },
  {
    name: "Denim Shirt",
    description: "Versatile denim shirt for casual wear.",
    category: "Men's Shirts",
    price: 74.99,
    images: ["https://images.unsplash.com/photo-1596400564269-f1a8b3c0ed47?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Light Blue", "Medium Blue", "Dark Blue"],
    stock: 55,
    rating: 4.6,
    material: "100% Denim",
    sku: "MEN-SH005"
  },
  {
    name: "Henley Shirt",
    description: "Classic henley with button placket.",
    category: "Men's Shirts",
    price: 44.99,
    images: ["https://images.unsplash.com/photo-1535687930308-53d9118c670a?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Navy", "Gray"],
    stock: 80,
    rating: 4.6,
    material: "100% Cotton",
    sku: "MEN-SH006"
  },
  {
    name: "Flannel Shirt",
    description: "Cozy flannel shirt perfect for layering.",
    category: "Men's Shirts",
    price: 64.99,
    images: ["https://images.unsplash.com/photo-1596400564269-f1a8b3c0ed47?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red Plaid", "Blue Plaid", "Green Plaid"],
    stock: 60,
    rating: 4.7,
    material: "100% Cotton",
    sku: "MEN-SH007"
  },
  {
    name: "Linen Shirt",
    description: "Breathable linen shirt for warm weather.",
    category: "Men's Shirts",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1596400564269-f1a8b3c0ed47?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Beige", "Light Blue"],
    stock: 50,
    rating: 4.5,
    material: "100% Linen",
    sku: "MEN-SH008"
  },
  {
    name: "Striped Long Sleeve",
    description: "Classic striped long sleeve shirt.",
    category: "Men's Shirts",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1596400564269-f1a8b3c0ed47?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy Stripe", "Blue Stripe", "Black Stripe"],
    stock: 65,
    rating: 4.6,
    material: "100% Cotton",
    sku: "MEN-SH009"
  },
  {
    name: "Casual Camp Collar Shirt",
    description: "Trendy camp collar shirt for casual style.",
    category: "Men's Shirts",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1596400564269-f1a8b3c0ed47?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Tropical Print", "Solid Colors", "Geometric"],
    stock: 45,
    rating: 4.5,
    material: "100% Cotton",
    sku: "MEN-SH010"
  },

  // ===== MEN'S PANTS (10) =====
  {
    name: "Classic Denim Jeans",
    description: "Timeless denim jeans perfect for casual wear.",
    category: "Men's Pants",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Light Blue", "Dark Blue", "Black"],
    stock: 80,
    rating: 4.8,
    material: "98% Cotton, 2% Elastane",
    sku: "MEN-PT001"
  },
  {
    name: "Chino Pants",
    description: "Versatile chino pants for casual and smart casual.",
    category: "Men's Pants",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Khaki", "Navy", "Black", "Olive"],
    stock: 75,
    rating: 4.7,
    material: "100% Cotton",
    sku: "MEN-PT002"
  },
  {
    name: "Dress Pants",
    description: "Professional dress pants for work.",
    category: "Men's Pants",
    price: 119.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Black", "Navy", "Gray", "Charcoal"],
    stock: 60,
    rating: 4.9,
    material: "95% Polyester, 5% Elastane",
    sku: "MEN-PT003"
  },
  {
    name: "Shorts",
    description: "Comfortable shorts for warm weather.",
    category: "Men's Pants",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["30", "32", "34", "36"],
    colors: ["Khaki", "Navy", "Black", "Gray"],
    stock: 85,
    rating: 4.6,
    material: "100% Cotton",
    sku: "MEN-PT004"
  },
  {
    name: "Cargo Pants",
    description: "Practical cargo pants with multiple pockets.",
    category: "Men's Pants",
    price: 84.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Olive", "Black", "Navy", "Gray"],
    stock: 65,
    rating: 4.5,
    material: "100% Cotton",
    sku: "MEN-PT005"
  },
  {
    name: "Jogger Pants",
    description: "Comfortable jogger pants for casual wear.",
    category: "Men's Pants",
    price: 64.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Navy"],
    stock: 70,
    rating: 4.6,
    material: "80% Cotton, 20% Polyester",
    sku: "MEN-PT006"
  },
  {
    name: "Linen Pants",
    description: "Breathable linen pants for warm weather.",
    category: "Men's Pants",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Beige", "White", "Navy"],
    stock: 45,
    rating: 4.7,
    material: "100% Linen",
    sku: "MEN-PT007"
  },
  {
    name: "Sweatpants",
    description: "Comfortable sweatpants for lounging.",
    category: "Men's Pants",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Navy"],
    stock: 75,
    rating: 4.5,
    material: "80% Cotton, 20% Polyester",
    sku: "MEN-PT008"
  },
  {
    name: "Leather Pants",
    description: "Bold leather pants for statement looks.",
    category: "Men's Pants",
    price: 149.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["30", "32", "34", "36"],
    colors: ["Black", "Brown"],
    stock: 20,
    rating: 4.7,
    material: "100% Leather",
    sku: "MEN-PT009"
  },
  {
    name: "Athletic Shorts",
    description: "Performance athletic shorts for sports.",
    category: "Men's Pants",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Gray"],
    stock: 80,
    rating: 4.6,
    material: "92% Polyester, 8% Spandex",
    sku: "MEN-PT010"
  },

  // ===== SHOES (13) =====
  {
    name: "Classic White Sneakers",
    description: "Timeless white sneakers perfect for casual wear.",
    category: "Shoes",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=800&fit=crop"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    colors: ["White", "White/Navy", "White/Black"],
    stock: 100,
    rating: 4.8,
    material: "Leather and Canvas",
    sku: "SHOE-001"
  },
  {
    name: "Running Shoes",
    description: "Comfortable running shoes with cushioned sole.",
    category: "Shoes",
    price: 129.99,
    discountPrice: 99.99,
    images: ["https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&h=800&fit=crop"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    colors: ["Black", "Blue", "White", "Red"],
    stock: 85,
    rating: 4.9,
    material: "Mesh and Synthetic",
    sku: "SHOE-002"
  },
  {
    name: "Ankle Boots",
    description: "Stylish ankle boots perfect for any season.",
    category: "Shoes",
    price: 129.99,
    discountPrice: 99.99,
    images: ["https://images.unsplash.com/photo-1543163521-9145f4c6bed0?w=600&h=800&fit=crop"],
    sizes: ["5", "6", "7", "8", "9", "10", "11"],
    colors: ["Black", "Brown", "Tan"],
    stock: 50,
    rating: 4.8,
    material: "Genuine Leather",
    sku: "SHOE-003"
  },
  {
    name: "Casual Loafers",
    description: "Comfortable loafers for professional and casual wear.",
    category: "Shoes",
    price: 109.99,
    images: ["https://images.unsplash.com/photo-1543163521-9145f4c6bed0?w=600&h=800&fit=crop"],
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Black", "Brown", "Navy"],
    stock: 60,
    rating: 4.7,
    material: "Leather",
    sku: "SHOE-004"
  },
  {
    name: "High Heels",
    description: "Elegant high heels for special occasions.",
    category: "Shoes",
    price: 119.99,
    images: ["https://images.unsplash.com/photo-1543163521-9145f4c6bed0?w=600&h=800&fit=crop"],
    sizes: ["5", "6", "7", "8", "9", "10"],
    colors: ["Black", "Red", "Nude"],
    stock: 40,
    rating: 4.9,
    material: "Leather",
    sku: "SHOE-005"
  },
  {
    name: "Flip Flops",
    description: "Comfortable flip flops for casual wear.",
    category: "Shoes",
    price: 34.99,
    images: ["https://images.unsplash.com/photo-1543163521-9145f4c6bed0?w=600&h=800&fit=crop"],
    sizes: ["5", "6", "7", "8", "9", "10"],
    colors: ["Black", "White", "Navy"],
    stock: 120,
    rating: 4.5,
    material: "Rubber",
    sku: "SHOE-006"
  },
  {
    name: "Sandals",
    description: "Practical sandals for warm weather.",
    category: "Shoes",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1543163521-9145f4c6bed0?w=600&h=800&fit=crop"],
    sizes: ["5", "6", "7", "8", "9", "10", "11"],
    colors: ["Black", "Brown", "Tan"],
    stock: 80,
    rating: 4.6,
    material: "Leather",
    sku: "SHOE-007"
  },
  {
    name: "Slip-On Sneakers",
    description: "Easy slip-on sneakers for convenience.",
    category: "Shoes",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=800&fit=crop"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    colors: ["Black", "White", "Navy"],
    stock: 75,
    rating: 4.7,
    material: "Canvas",
    sku: "SHOE-008"
  },
  {
    name: "Formal Dress Shoes",
    description: "Professional dress shoes for formal events.",
    category: "Shoes",
    price: 139.99,
    images: ["https://images.unsplash.com/photo-1543163521-9145f4c6bed0?w=600&h=800&fit=crop"],
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Black", "Brown"],
    stock: 45,
    rating: 4.8,
    material: "Leather",
    sku: "SHOE-009"
  },
  {
    name: "Hiking Boots",
    description: "Durable hiking boots for outdoor adventures.",
    category: "Shoes",
    price: 149.99,
    images: ["https://images.unsplash.com/photo-1543163521-9145f4c6bed0?w=600&h=800&fit=crop"],
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Brown", "Black", "Gray"],
    stock: 55,
    rating: 4.9,
    material: "Leather and Synthetic",
    sku: "SHOE-010"
  },
  {
    name: "Boat Shoes",
    description: "Classic boat shoes for casual nautical style.",
    category: "Shoes",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1543163521-9145f4c6bed0?w=600&h=800&fit=crop"],
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Navy", "Brown", "White"],
    stock: 65,
    rating: 4.6,
    material: "Leather",
    sku: "SHOE-011"
  },
  {
    name: "Platform Boots",
    description: "Trendy platform boots for fashion-forward looks.",
    category: "Shoes",
    price: 134.99,
    images: ["https://images.unsplash.com/photo-1543163521-9145f4c6bed0?w=600&h=800&fit=crop"],
    sizes: ["5", "6", "7", "8", "9", "10"],
    colors: ["Black", "Brown"],
    stock: 40,
    rating: 4.7,
    material: "Synthetic",
    sku: "SHOE-012"
  },
  {
    name: "Canvas Shoes",
    description: "Casual canvas shoes for everyday wear.",
    category: "Shoes",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=800&fit=crop"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    colors: ["Black", "White", "Navy", "Red"],
    stock: 90,
    rating: 4.5,
    material: "Canvas",
    sku: "SHOE-013"
  },

  // ===== BAGS & ACCESSORIES (12) =====
  {
    name: "Leather Handbag",
    description: "Stylish leather handbag for everyday use.",
    category: "Bags & Accessories",
    price: 159.99,
    discountPrice: 129.99,
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["Black", "Brown", "Burgundy"],
    stock: 40,
    rating: 4.8,
    material: "Genuine Leather",
    sku: "BAG-001"
  },
  {
    name: "Crossbody Bag",
    description: "Practical crossbody bag for on-the-go.",
    category: "Bags & Accessories",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["Black", "Tan", "Red"],
    stock: 55,
    rating: 4.7,
    material: "PU Leather",
    sku: "BAG-002"
  },
  {
    name: "Backpack",
    description: "Versatile backpack for daily and travel use.",
    category: "Bags & Accessories",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["Black", "Navy", "Gray"],
    stock: 70,
    rating: 4.6,
    material: "Nylon",
    sku: "BAG-003"
  },
  {
    name: "Leather Belt",
    description: "Classic leather belt to cinch your waist.",
    category: "Bags & Accessories",
    price: 64.99,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Brown", "Cognac"],
    stock: 90,
    rating: 4.7,
    material: "Genuine Leather",
    sku: "BAG-004"
  },
  {
    name: "Sunglasses",
    description: "Trendy sunglasses with UV protection.",
    category: "Bags & Accessories",
    price: 89.99,
    images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["Black", "Brown", "Rose Gold"],
    stock: 75,
    rating: 4.7,
    material: "Plastic Frame",
    sku: "BAG-005"
  },
  {
    name: "Watch",
    description: "Classic watch perfect for any occasion.",
    category: "Bags & Accessories",
    price: 149.99,
    discountPrice: 119.99,
    images: ["https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["Black", "Silver", "Gold"],
    stock: 50,
    rating: 4.9,
    material: "Stainless Steel",
    sku: "BAG-006"
  },
  {
    name: "Silk Scarf",
    description: "Luxurious silk scarf to elevate any outfit.",
    category: "Bags & Accessories",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1508409072014-5a3195a36cff?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["Floral", "Solid Colors", "Geometric"],
    stock: 80,
    rating: 4.8,
    material: "100% Silk",
    sku: "BAG-007"
  },
  {
    name: "Beanie Hat",
    description: "Cozy beanie hat for winter.",
    category: "Bags & Accessories",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1459515885857-a1efb6934eca?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["Black", "Gray", "Navy", "Cream"],
    stock: 100,
    rating: 4.6,
    material: "Acrylic",
    sku: "BAG-008"
  },
  {
    name: "Gold Necklace",
    description: "Elegant gold necklace for sophistication.",
    category: "Bags & Accessories",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1535632066927-ab7348c28242?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["Gold", "Rose Gold", "Silver"],
    stock: 60,
    rating: 4.9,
    material: "14K Gold Plated",
    sku: "BAG-009"
  },
  {
    name: "Leather Gloves",
    description: "Soft leather gloves for warmth and style.",
    category: "Bags & Accessories",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1598920917128-f2fe22dcc52d?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Brown", "Burgundy"],
    stock: 50,
    rating: 4.8,
    material: "Genuine Leather",
    sku: "BAG-010"
  },
  {
    name: "Pearl Earrings",
    description: "Classic pearl earrings for elegance.",
    category: "Bags & Accessories",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["White Pearl", "Black Pearl"],
    stock: 70,
    rating: 4.9,
    material: "Freshwater Pearl",
    sku: "BAG-011"
  },
  {
    name: "Canvas Tote Bag",
    description: "Durable canvas tote for shopping.",
    category: "Bags & Accessories",
    price: 44.99,
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["Black", "Natural", "Navy"],
    stock: 85,
    rating: 4.5,
    material: "Canvas",
    sku: "BAG-012"
  },

  // ===== ACTIVEWEAR (10) =====
  {
    name: "Yoga Leggings",
    description: "Comfortable yoga leggings with high waist.",
    category: "Activewear",
    price: 84.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Gray", "Purple"],
    stock: 70,
    rating: 4.8,
    material: "92% Nylon, 8% Spandex",
    sku: "ACT-001"
  },
  {
    name: "Sports Bra",
    description: "Supportive sports bra for high-impact activities.",
    category: "Activewear",
    price: 64.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Gray", "Navy"],
    stock: 65,
    rating: 4.9,
    material: "85% Nylon, 15% Spandex",
    sku: "ACT-002"
  },
  {
    name: "Gym T-Shirt",
    description: "Breathable gym t-shirt for workouts.",
    category: "Activewear",
    price: 44.99,
    images: ["https://images.unsplash.com/photo-1535687930308-53d9118c670a?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray"],
    stock: 90,
    rating: 4.6,
    material: "88% Polyester, 12% Spandex",
    sku: "ACT-003"
  },
  {
    name: "Workout Jacket",
    description: "Lightweight jacket for pre and post-workout.",
    category: "Activewear",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Gray"],
    stock: 50,
    rating: 4.7,
    material: "90% Polyester, 10% Spandex",
    sku: "ACT-004"
  },
  {
    name: "Running Shorts",
    description: "Lightweight shorts for running.",
    category: "Activewear",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Purple"],
    stock: 75,
    rating: 4.6,
    material: "88% Polyester, 12% Spandex",
    sku: "ACT-005"
  },
  {
    name: "Tank Top",
    description: "Sleeveless tank top for workouts.",
    category: "Activewear",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1535687930308-53d9118c670a?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Navy"],
    stock: 85,
    rating: 4.5,
    material: "92% Polyester, 8% Spandex",
    sku: "ACT-006"
  },
  {
    name: "Gym Shorts",
    description: "Comfortable shorts for gym workouts.",
    category: "Activewear",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Gray", "Navy"],
    stock: 80,
    rating: 4.6,
    material: "88% Polyester, 12% Spandex",
    sku: "ACT-007"
  },
  {
    name: "Sweatpants",
    description: "Comfortable sweatpants for casual workouts.",
    category: "Activewear",
    price: 64.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Navy"],
    stock: 70,
    rating: 4.7,
    material: "80% Cotton, 20% Polyester",
    sku: "ACT-008"
  },
  {
    name: "Fitness Crop Top",
    description: "Supportive crop top for fitness.",
    category: "Activewear",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1535687930308-53d9118c670a?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Purple"],
    stock: 60,
    rating: 4.8,
    material: "85% Nylon, 15% Spandex",
    sku: "ACT-009"
  },
  {
    name: "Hoodie",
    description: "Cozy hoodie perfect for workouts.",
    category: "Activewear",
    price: 84.99,
    images: ["https://images.unsplash.com/photo-1556821840-9c63d3f02f65?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Navy"],
    stock: 55,
    rating: 4.7,
    material: "80% Cotton, 20% Polyester",
    sku: "ACT-010"
  },

  // ===== SWIMWEAR (10) =====
  {
    name: "One-Piece Swimsuit",
    description: "Classic one-piece swimsuit for swimming.",
    category: "Swimwear",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Blue", "Red"],
    stock: 50,
    rating: 4.7,
    material: "82% Nylon, 18% Spandex",
    sku: "SWM-001"
  },
  {
    name: "Bikini Set",
    description: "Stylish bikini set for beach.",
    category: "Swimwear",
    price: 64.99,
    images: ["https://images.unsplash.com/photo-1612336307429-8a88e8d08dbb?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Floral", "Tropical", "Solid"],
    stock: 65,
    rating: 4.8,
    material: "82% Nylon, 18% Spandex",
    sku: "SWM-002"
  },
  {
    name: "Swim Shorts",
    description: "Comfortable swim shorts for men.",
    category: "Swimwear",
    price: 54.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Black", "Tropical", "Solid"],
    stock: 75,
    rating: 4.6,
    material: "100% Polyester",
    sku: "SWM-003"
  },
  {
    name: "Rash Guard",
    description: "Protective rash guard for water sports.",
    category: "Swimwear",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1535687930308-53d9118c670a?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Blue", "Navy"],
    stock: 60,
    rating: 4.7,
    material: "88% Nylon, 12% Spandex",
    sku: "SWM-004"
  },
  {
    name: "Beach Cover-Up",
    description: "Lightweight cover-up for the beach.",
    category: "Swimwear",
    price: 49.99,
    images: ["https://images.unsplash.com/photo-1595607774223-ef52624120d2?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["White", "Navy", "Floral"],
    stock: 70,
    rating: 4.5,
    material: "100% Polyester",
    sku: "SWM-005"
  },
  {
    name: "Swim Leggings",
    description: "Full-coverage swim leggings.",
    category: "Swimwear",
    price: 74.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Tropical"],
    stock: 55,
    rating: 4.6,
    material: "82% Nylon, 18% Spandex",
    sku: "SWM-006"
  },
  {
    name: "High-Waisted Bikini",
    description: "Trendy high-waisted bikini.",
    category: "Swimwear",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1612336307429-8a88e8d08dbb?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Red", "Floral"],
    stock: 50,
    rating: 4.8,
    material: "82% Nylon, 18% Spandex",
    sku: "SWM-007"
  },
  {
    name: "Swim Trunks",
    description: "Stylish swim trunks for men.",
    category: "Swimwear",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Black", "Tropical", "Geometric"],
    stock: 65,
    rating: 4.6,
    material: "100% Polyester",
    sku: "SWM-008"
  },
  {
    name: "Tankini",
    description: "Comfortable tankini for modest coverage.",
    category: "Swimwear",
    price: 84.99,
    images: ["https://images.unsplash.com/photo-1612336307429-8a88e8d08dbb?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Floral"],
    stock: 45,
    rating: 4.7,
    material: "82% Nylon, 18% Spandex",
    sku: "SWM-009"
  },
  {
    name: "Swim Cap",
    description: "Protective swim cap for water activities.",
    category: "Swimwear",
    price: 29.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["One Size"],
    colors: ["Black", "Navy", "White", "Blue"],
    stock: 100,
    rating: 4.5,
    material: "Silicone",
    sku: "SWM-010"
  },

  // ===== CASUAL WEAR (10) =====
  {
    name: "Graphic T-Shirt",
    description: "Fun graphic t-shirt for casual wear.",
    category: "Casual Wear",
    price: 39.99,
    images: ["https://images.unsplash.com/photo-1535687930308-53d9118c670a?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Navy"],
    stock: 85,
    rating: 4.6,
    material: "100% Cotton",
    sku: "CAS-001"
  },
  {
    name: "Hoodie Sweatshirt",
    description: "Comfortable hoodie for casual comfort.",
    category: "Casual Wear",
    price: 74.99,
    images: ["https://images.unsplash.com/photo-1556821840-9c63d3f02f65?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Gray", "Black", "Navy", "Burgundy"],
    stock: 70,
    rating: 4.7,
    material: "80% Cotton, 20% Polyester",
    sku: "CAS-002"
  },
  {
    name: "Denim Overall",
    description: "Trendy denim overall for casual look.",
    category: "Casual Wear",
    price: 99.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Blue", "Dark Blue"],
    stock: 45,
    rating: 4.5,
    material: "100% Denim",
    sku: "CAS-003"
  },
  {
    name: "Casual Jumpsuit",
    description: "Comfortable jumpsuit for casual outings.",
    category: "Casual Wear",
    price: 84.99,
    images: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Olive"],
    stock: 50,
    rating: 4.6,
    material: "100% Cotton",
    sku: "CAS-004"
  },
  {
    name: "Denim Overalls",
    description: "Classic denim overalls for vintage style.",
    category: "Casual Wear",
    price: 94.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Blue", "Dark Blue"],
    stock: 55,
    rating: 4.7,
    material: "100% Denim",
    sku: "CAS-005"
  },
  {
    name: "Casual Blazer",
    description: "Relaxed casual blazer for smart casual.",
    category: "Casual Wear",
    price: 119.99,
    images: ["https://images.unsplash.com/photo-1539533057440-7bf05ad00029?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Gray"],
    stock: 40,
    rating: 4.8,
    material: "85% Polyester, 15% Cotton",
    sku: "CAS-006"
  },
  {
    name: "Linen Shorts",
    description: "Breathable linen shorts for summer.",
    category: "Casual Wear",
    price: 64.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Beige", "White", "Navy"],
    stock: 60,
    rating: 4.6,
    material: "100% Linen",
    sku: "CAS-007"
  },
  {
    name: "Casual Vest",
    description: "Lightweight vest for layering.",
    category: "Casual Wear",
    price: 69.99,
    images: ["https://images.unsplash.com/photo-1539533057440-7bf05ad00029?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Tan"],
    stock: 50,
    rating: 4.5,
    material: "100% Cotton",
    sku: "CAS-008"
  },
  {
    name: "Parachute Pants",
    description: "Trendy parachute pants for casual style.",
    category: "Casual Wear",
    price: 79.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Olive"],
    stock: 55,
    rating: 4.6,
    material: "100% Nylon",
    sku: "CAS-009"
  },
  {
    name: "Casual T-Shirt Dress",
    description: "Simple t-shirt dress for casual comfort.",
    category: "Casual Wear",
    price: 59.99,
    images: ["https://images.unsplash.com/photo-1535687930308-53d9118c670a?w=600&h=800&fit=crop"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    stock: 70,
    rating: 4.5,
    material: "100% Cotton",
    sku: "CAS-010"
  }
];

export default sampleProducts;
